### ISSUE TITLE
getTable returns empty result

### ISSUE THREAD

**Issue by rltaxandria** [mehmet-kozan/pdf-parse#48]
Like the title says. I decided to try out your package in a very basic nodejs app because I like to extract data from a timesheet pdf but the resulting JSON has an empty `tables` array. Below you can find the js script I use as well as the JSON output.

```js
import { PDFParse } from "pdf-parse";

const parser = new PDFParse({ url: './debug.pdf' });
const tables = await parser.getTable();

console.log(JSON.stringify(tables, null, "\t"));
```

```json
{
	"pages": [
		{
			"num": 1,
			"tables": []
		}
	],
	"mergedTables": [],
	"total": 1
}
```

I added the PDF file I use as attachment. You can find it here: [debug.pdf](https://github.com/user-attachments/files/23387913/debug.pdf). The version I am using is `^2.4.5`.

**Comment by rltaxandria** [comment]
Also something I think is important to share is that when I run `await parser.getText()` I actually do get a result.

```
Header1 Header2 Header3
Test1 Test2 Test3
Test4 Test5 Test6
Test7 Test8 Test9
Test10 Test11 Test12

-- 1 of 1 --
```

**Comment by kivanc17** [comment]
I also encountered the same problem.
```
TableResult {
  pages: [
    { num: 1, tables: [] },
    { num: 2, tables: [] },
    { num: 3, tables: [] }
  ],
  mergedTables: [],
  total: 3
}
```

Although getText returns a full result, getTable returns an empty result.

**Comment by rltaxandria** [comment]
Hey @mehmet-kozan, any updates on this one? I noticed you implemented a change in PR #63 that should fix this but you have not released a new version after that. I really like how this library works, it is by far one of the better solutions out there. :)

**Comment by mehmet-kozan** [comment]
@rltaxandria I will release a new version within a week, and this issue will be resolved.

**Comment by kivanc17** [comment]
@mehmet-kozan Is there any progress? It still isn't working properly.

**Comment by anshulupadhyay03** [comment]
@mehmet-kozan any update on the progress? Waiting for this work.
